backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "/static/files/"
public_folder: "/files/"

collections:
  - name: "about"
    label: "About"
    folder: "src/pages/about"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Content Type",
          name: "contentType",
          widget: "hidden",
          default: "about",
        }
      - { label: "Path", name: "path", widget: "hidden", default: "/about" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "home"
    label: "Home"
    folder: "src/pages/home"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Content Type",
          name: "contentType",
          widget: "hidden",
          default: "about",
        }
      - { label: "Path", name: "path", widget: "hidden", default: "/" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "coaching"
    label: "Coaching"
    folder: "src/pages/coaching"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Content Type",
          name: "contentType",
          widget: "hidden",
          default: "coaching",
        }
      - { label: "Path", name: "path", widget: "hidden", default: "/coaching" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "offerings"
    label: "Offerings"
    folder: "src/pages/offerings"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Content Type",
          name: "contentType",
          widget: "hidden",
          default: "offerings",
        }
      - { label: "Path", name: "path", widget: "hidden", default: "/offerings" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "PersonalTitle", name: "title", widget: "string" }
      - { label: "PersonalBody", name: "body", widget: "markdown" }
      - { label: "GroupTitle", name: "title", widget: "string" }
      - { label: "GroupBody", name: "body", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }